### ISSUE TITLE
Add airflow 2.4.x support

### ISSUE THREAD

**Issue by pvaling** [bryzgaloff/airflow-clickhouse-plugin#47]
Its tricky to upgrade airflow version tо 2.4 with current airflow-clickhouse-plugin. Pip install forces downgrade to airflow-2.3.4.

**Comment by bryzgaloff** [comment]
Hi @pvaling, yes, we have a restriction on upper bound of Airflow versions to . We are working on migration to Airflow 2.4 in this PR: #44

It is tricky to support a wide variety of versions (including Python versions), so there we discuss how to handle all of them properly.

**Comment by bryzgaloff** [comment]
Done as a part of #50. Airflow 2.4 support is released: https://pypi.org/project/airflow-clickhouse-plugin/0.9.0/

Though, Airflow 2.1 support is disabled, details: #52
