### ISSUE TITLE
Support for airflow 2.5.0?

### ISSUE THREAD

**Issue by electrical** [bryzgaloff/airflow-clickhouse-plugin#59]
Hi,

Airflow 2.5.0 was released earlier this month.
At the moment we can't use it because of the dependencies in this project.
Are there plans to test it with 2.5.0 and update the package?

Thanks!

**Comment by bryzgaloff** [comment]
Will potentially do it in a week or so. Contribution is welcome! :)

We have auto-tests, so you may make a simple contribution with a version bump, and I will approve the CI pipeline to run.

Do not forget to also update a versions matrix in README and also in the workflow code.

**Comment by electrical** [comment]
Thanks! will have a look at the required changes to at least run the tests. Not sure what further changes might be required for 2.5.0

**Comment by bryzgaloff** [comment]
Yes, quite often it is as simple as a just increasing the version. I would recommend you to clone the `airflow-clickhouse-plugin`, install Airflow 2.5.0 and `clickhouse-driver` (via simple `pip install`) and run the tests to check locally if it works. And make changes if not.

**Comment by bryzgaloff** [comment]
Released: https://github.com/bryzgaloff/airflow-clickhouse-plugin/releases/tag/v0.10.0
