### ISSUE TITLE
support for airflow 2.6.0

### ISSUE THREAD

**Issue by CorsettiS** [bryzgaloff/airflow-clickhouse-plugin#65]
airflow 2.6.0 has just released and unfortunately the clickhouse plugin cannot be installed on it. It would be interesting to add support for airflow 2.6.0 then. from my understanding, since nothing was removed from 2.5.x to 2.6.x, it should be required to just loose up the requirements of the package installation to allow airflow 2.6.x and it should work out of the box no?

**Comment by bryzgaloff** [comment]
Hi @CorsettiS yes, loosening the requirements sounds working to me, could you please give it a try as a PR? We have a CI pipeline with tests configured in the repo, so it should be auto-tested and confirm that it works.

**Comment by CorsettiS** [comment]
@bryzgaloff of course ! just opened a [PR](https://github.com/bryzgaloff/airflow-clickhouse-plugin/pull/66) and all tests worked fine

**Comment by bryzgaloff** [comment]
Resolved in #66, thank you for your contribution! 👏
