### ISSUE TITLE
Bug in 0.10.1 in get_pandas_df

### ISSUE THREAD

**Issue by amolsr** [bryzgaloff/airflow-clickhouse-plugin#84]
```
   def get_pandas_df(self, sql: str):
        import pandas as pd
        rows, columns_defs = self.run(sql, with_column_types=True)
        columns = [column_name for column_name, _ in columns_defs]
        return pd.DataFrame(rows, columns=columns)
```
I need to use the jinja templeting in this but get_pandas_df doesn't accept parameters which should be passed down to run function.

**Comment by amolsr** [comment]
https://github.com/bryzgaloff/airflow-clickhouse-plugin/pull/85

**Comment by bryzgaloff** [comment]
Hi @amolsr versions below the latest are not actively supported. I insist on using the latest available version of Airflow and plugins. If 0.10 is a requirements for you, feel free to create a fork from the version you require and keep supporting as a separate GitHub/PyPI project.
