### ISSUE TITLE
Question: Try http support

### ISSUE THREAD

**Issue by caicancai** [bryzgaloff/airflow-clickhouse-plugin#91]
Hello, thank you very much for open sourcing this project. I learned a lot.
I am trying to support http recently. My main change is to modify the clickhouse driver, from clickhouse-driver -> clickhouse-connect, but I encountered some problems.
When I execute DAG tasks, CA certificate verification always fails, but my local test is normal. Is this a problem with airflow?
I tried pythonoperator and simeplehttpoperator to execute http requests and the same problem.

relate to: https://github.com/apache/airflow/discussions/45256

**Comment by bryzgaloff** [comment]
Hi Cancai, thank you for your kind words :)

I had the same issue and usually used `secure=False` in ClickHouse client settings to overcome that as a temporary solution. I applied additional security layer instead to protect the connection, so its was pretty safe in my case. However, I have not investigated this issue further myself. I believe there should be some related issues in clickhouse-driver or Airflow.

I am closing the issue as a non-related to the plugin but you feel free to send additional comments, I should stay subscribed and get notified.

**Comment by caicancai** [comment]
Thank you for your reply. I suspect that airflow has some problems with its support for the http protocol, because I tested the redis plug-in and found related problems. Currently, it seems that there is no problem with tcp.
Thank you again for your patient answer

**Comment by caicancai** [comment]
@bryzgaloff Hi,
I have located the problem. In the new version https://github.com/urllib3/urllib3, the length requirement for the CA verification certificate is 2048 bytes. I tried to modify the certificate from 1024 bytes to 2048 bytes. It seems to be effective. I don't know if TCP has similar problems.

**Comment by bryzgaloff** [comment]
Hi @caicancai great to know, thank you for sharing! At least I will use it next time with the HTTP ClickHouse operator :)
